// <auto-generated />
namespace UILHost.Infrastructure.Data.Operational.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CodeToTeacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CodeToTeacher));
        
        string IMigrationMetadata.Id
        {
            get { return "201408110454488_CodeToTeacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
